### ISSUE TITLE
Laravel Setup

### ISSUE THREAD

**Issue by AvidProlix** [qrogers6/cs4420_database_systems#1]
See how to implement laravel with PHP and phpMyAdmin. 
See if Laravel is viable.

**Comment by qrogers6** [comment]
Probably should look into how to deploy it to an actual website for production.

**Comment by AvidProlix** [comment]
Need to convert to using PHP 5.4

**Comment by qrogers6** [comment]
Are we going to continue to work on getting the Laravel framework implemented?

**Comment by AvidProlix** [comment]
yeah, we should be able to deploy to the server as well

**Comment by AvidProlix** [comment]
Laravel is setup in estrickl branch. it remains in the branch since the setup breaks the current database connection method for logging in. The branch has completed connecting to, managing, and seeding the database, as well as a views using blade layouts.
