### ISSUE TITLE
GUI Sketches

### ISSUE THREAD

**Issue by AvidProlix** [qrogers6/cs4420_database_systems#5]
Front end sketches of how the site will look, the three tabs of different explanation levels, A user page, etc.
If you are feeling ambitious: https://www.invisionapp.com is good for making GUI sketches.

**Comment by roliynyk** [comment]
Home page
![gui](https://user-images.githubusercontent.com/25214833/46588373-5104c500-ca58-11e8-9e49-ac6fe4b7064f.JPG)
