### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by AvidProlix** [qrogers6/cs4420_database_systems#6]
Define what tables are needed and how they interact with one another.
ie. User table, and Posts table.
Define what attributes are required for each table

**Comment by qrogers6** [comment]
Add the new attributes for the user table you created to the existing profiles table I have created. This is done through phpmyadmin.

cs4420_database_systems/database/profiles.txt

id and username/name work similar so the id is unnecessary.

email_verifies could be a boolean
